# Generated by Django 2.2.3 on 2019-08-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfsubcodeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcode',
            old_name='title',
            new_name='something',
        ),
    ]
