# Generated by Django 2.2.3 on 2019-08-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfsubcodeapi', '0003_auto_20190813_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcode',
            name='something',
        ),
    ]
