# Generated by Django 2.2.3 on 2019-08-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapisubcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
